services:
  api-gateway:
    image: api-gateway
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
      - postgres
      - redis
  auth-service:
    image: auth-service
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - redis
      - rabbitmq

  transaction-service:
    image: transaction-service
    build:
      context: ./transaction-service
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    depends_on:
      - postgres
      - redis
      - rabbitmq

  exchange-service:
    image: exchange-service
    build:
      context: ./exchange-service
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    depends_on:
      - postgres
      - redis
      - rabbitmq

  gift-code-service:
    image: gift-code-service
    build:
      context: ./gift-code-service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - postgres
      - redis
      - rabbitmq


  wallet-service:
    image: wallet-service
    build:
      context: ./wallet-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - redis
      - rabbitmq

  eureka-server:
    image: eureka-server
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: wallet_system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - ./init_data.sql:/docker-entrypoint-initdb.d/init_data.sql
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  postgres_data:
