server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
#    gateway:
#      routes:
#        - id: auth-service
#          predicates:
#            - Path=/api/auth/**
#          uri: lb://auth-service:8081
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

jwt:
  secret: ThisIsAVerySecureSecretKeyForJWTSigningInOurWalletTransferSystem

management:
  endpoints:
    web:
      exposure:
        include: health,info