# src/main/resources/application.yml
spring:
  application:
    name: wallet-service
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/wallet_system}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: wallet_schema
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: wallet_schema
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

server:
  port: ${SERVER_PORT:8082}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

# RabbitMQ configuration
rabbitmq:
  exchange:
    transactions: wallet.transaction.exchange
    user-events: wallet.user.exchange
  queue:
    transactions: wallet.transaction.queue
    user-created: wallet.user.created.queue
  routing-key:
    transaction-created: wallet.transaction.created
    user-created: wallet.user.created
jwt:
  secret: ThisIsAVerySecureSecretKeyForJWTSigningInOurWalletTransferSystem